# Generated by Django 4.1.7 on 2023-03-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("duplicate_detection", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Choice",),
        migrations.DeleteModel(name="Question",),
    ]
