# Generated by Django 4.1.7 on 2023-03-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("duplicate_detection", "0002_delete_choice_delete_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="bugReportDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bugReport", models.CharField(max_length=200)),
            ],
        ),
    ]
