# Generated by Django 4.1.7 on 2023-03-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duplicate_detection", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BugReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(name="bugReportDescription",),
    ]
